### ISSUE TITLE
Filtering by Tags and Milestones

### ISSUE THREAD

**Issue by sherimoore** [krmorse/StoryReleaseTracking#1]
Hi @krmorse Amy says that this app needs to be whitelisted so that we can filter on Tags and Milestones.  Is that something that can easily be done?

**Comment by krmorse** [comment]
@sherimoore, easy peasy.

Would you mind testing the fix? I'll merge the pull request if it looks good to you.

https://raw.githubusercontent.com/krmorse/StoryReleaseTracking/5dde58d59de680705288ecf331bfb61b8429a550/deploy/App-uncompressed.html

**Comment by sherimoore** [comment]
@krmorse Looks great, thank you so much!

**Comment by krmorse** [comment]
Great!  This was the perfect little Thursday afternoon side project.  Thanks for the idea!
